// Per-dialect keyword / function vocabularies for the autocomplete suggester
// (sqlSuggest.ts). Split out of sqlSuggest so the ranking core stays small and
// the word lists can grow per engine without touching the algorithm.
//
// SHAPE: a shared ANSI CORE that every SQL engine understands, plus an EXTRAS
// table keyed by Engine holding only that dialect's own syntax. `keywordsFor`
// concatenates core + extras — EXCEPT for Cassandra, whose CQL is a subset with
// its own spelling (no joins, no subqueries), so it REPLACES the core outright
// rather than adding to it. Suggesting `RIGHT JOIN` in a CQL editor is worse
// than suggesting nothing.
//
// ORDER IS THE RANKING. sqlSuggest returns matches in array order (nothing
// re-sorts downstream), so the most-used words come first within each list and
// core words outrank dialect extras on an equal prefix.
//
// CASE: entries are inserted verbatim. SQL words are upper-case (house style,
// matching formatSql); ClickHouse's camelCase functions are NOT uppercased —
// `toDateTime` is a different identifier from `TODATETIME` there.

import type { Engine } from "../../../shared/types";

/**
 * Keywords every supported SQL engine shares. Ordered roughly by how often a
 * user types them (clause keywords first, then DML, then DDL).
 */
const CORE_KEYWORDS = [
  "SELECT",
  "FROM",
  "WHERE",
  "GROUP BY",
  "ORDER BY",
  "HAVING",
  "LIMIT",
  "OFFSET",
  "AS",
  "ON",
  "USING",
  "AND",
  "OR",
  "NOT",
  "IN",
  "NOT IN",
  "IS NULL",
  "IS NOT NULL",
  "LIKE",
  "NOT LIKE",
  "BETWEEN",
  "EXISTS",
  "NOT EXISTS",
  "DISTINCT",
  "JOIN",
  "LEFT JOIN",
  "LEFT OUTER JOIN",
  "RIGHT JOIN",
  "INNER JOIN",
  "FULL OUTER JOIN",
  "CROSS JOIN",
  "UNION",
  "UNION ALL",
  "INTERSECT",
  "EXCEPT",
  "ASC",
  "DESC",
  "CASE",
  "CASE WHEN",
  "WHEN",
  "THEN",
  "ELSE",
  "END",
  "WITH",
  "OVER",
  "PARTITION BY",
  "ROWS BETWEEN",
  "UNBOUNDED PRECEDING",
  "CURRENT ROW",
  "CAST",
  "NULL",
  "TRUE",
  "FALSE",
  "INSERT INTO",
  "VALUES",
  "UPDATE",
  "SET",
  "DELETE FROM",
  "CREATE TABLE",
  "CREATE TABLE IF NOT EXISTS",
  "CREATE VIEW",
  "CREATE INDEX",
  "CREATE UNIQUE INDEX",
  "ALTER TABLE",
  "ADD COLUMN",
  "DROP COLUMN",
  "DROP TABLE",
  "DROP TABLE IF EXISTS",
  "DROP VIEW",
  "DROP INDEX",
  "TRUNCATE TABLE",
  "EXPLAIN",
  "PRIMARY KEY",
  "FOREIGN KEY",
  "REFERENCES",
  "UNIQUE",
  "NOT NULL",
  "DEFAULT",
  "CHECK",
  "CONSTRAINT",
  "BEGIN",
  "COMMIT",
  "ROLLBACK",
  "SAVEPOINT",
];

/** Aggregate / scalar functions every engine has. The trailing `(` is part of
 *  the insert so the caret lands inside the parens (no trailing space). */
const CORE_FUNCTIONS = [
  "COUNT(",
  "SUM(",
  "AVG(",
  "MIN(",
  "MAX(",
  "COALESCE(",
  "NULLIF(",
  "LENGTH(",
  "LOWER(",
  "UPPER(",
  "TRIM(",
  "ABS(",
  "ROUND(",
  "FLOOR(",
  "CEIL(",
  "CONCAT(",
  "REPLACE(",
  "SUBSTRING(",
  "CAST(",
  "ROW_NUMBER(",
  "RANK(",
  "DENSE_RANK(",
  "LAG(",
  "LEAD(",
];

/** CQL's own vocabulary — REPLACES the core (see file header). */
const CQL_KEYWORDS = [
  "SELECT",
  "FROM",
  "WHERE",
  "AND",
  "IN",
  "ORDER BY",
  "LIMIT",
  "PER PARTITION LIMIT",
  "ALLOW FILTERING",
  "GROUP BY",
  "ASC",
  "DESC",
  "AS",
  "DISTINCT",
  "CONTAINS",
  "CONTAINS KEY",
  "TOKEN",
  "JSON",
  "SELECT JSON",
  "INSERT INTO",
  "INSERT JSON",
  "VALUES",
  "IF NOT EXISTS",
  "USING TTL",
  "USING TIMESTAMP",
  "UPDATE",
  "SET",
  "IF EXISTS",
  "DELETE FROM",
  "BEGIN BATCH",
  "BEGIN UNLOGGED BATCH",
  "APPLY BATCH",
  "USE",
  "DESCRIBE",
  "TRUNCATE",
  "CREATE KEYSPACE",
  "CREATE TABLE",
  "CREATE TABLE IF NOT EXISTS",
  "PRIMARY KEY",
  "WITH CLUSTERING ORDER BY",
  "CREATE INDEX",
  "CREATE CUSTOM INDEX",
  "CREATE MATERIALIZED VIEW",
  "CREATE TYPE",
  "ALTER TABLE",
  "ADD",
  "RENAME",
  "DROP TABLE",
  "DROP KEYSPACE",
  "DROP INDEX",
  "STATIC",
  "COUNTER",
  "FROZEN",
];

const CQL_FUNCTIONS = [
  "COUNT(",
  "SUM(",
  "AVG(",
  "MIN(",
  "MAX(",
  "TOKEN(",
  "TTL(",
  "WRITETIME(",
  "NOW(",
  "UUID(",
  "CAST(",
  "toTimestamp(",
  "toDate(",
  "toUnixTimestamp(",
  "blobAsText(",
  "textAsBlob(",
];

/** Dialect-only keywords, appended after the core. */
const KEYWORD_EXTRAS: Partial<Record<Engine, string[]>> = {
  postgres: [
    "ILIKE",
    "NOT ILIKE",
    "RETURNING",
    "ON CONFLICT",
    "ON CONFLICT DO NOTHING",
    "ON CONFLICT DO UPDATE SET",
    "EXCLUDED",
    "DISTINCT ON",
    "WITH RECURSIVE",
    "LATERAL",
    "FILTER (WHERE",
    "SIMILAR TO",
    "NULLS FIRST",
    "NULLS LAST",
    "FOR UPDATE",
    "FOR SHARE",
    "WINDOW",
    "TABLESAMPLE",
    "GENERATED ALWAYS AS IDENTITY",
    "SERIAL",
    "BIGSERIAL",
    "JSONB",
    "TEXT",
    "TIMESTAMPTZ",
    "EXPLAIN ANALYZE",
    "CREATE SCHEMA",
    "CREATE MATERIALIZED VIEW",
    "REFRESH MATERIALIZED VIEW",
    "CREATE OR REPLACE VIEW",
    "CREATE EXTENSION",
    "ANALYZE",
    "VACUUM",
    "COPY",
    "GRANT",
    "REVOKE",
    "SET search_path TO",
  ],
  mysql: [
    "SHOW TABLES",
    "SHOW DATABASES",
    "SHOW COLUMNS FROM",
    "SHOW CREATE TABLE",
    "SHOW INDEX FROM",
    "SHOW PROCESSLIST",
    "DESCRIBE",
    "USE",
    "ON DUPLICATE KEY UPDATE",
    "INSERT IGNORE INTO",
    "REPLACE INTO",
    "WITH RECURSIVE",
    "STRAIGHT_JOIN",
    "FORCE INDEX",
    "FOR UPDATE",
    "LOCK IN SHARE MODE",
    "AUTO_INCREMENT",
    "MODIFY COLUMN",
    "CHANGE COLUMN",
    "CHARACTER SET",
    "COLLATE",
    "ENGINE = InnoDB",
    "UNSIGNED",
    "CREATE DATABASE",
    "DROP DATABASE",
    "EXPLAIN ANALYZE",
    "START TRANSACTION",
  ],
  sqlite: [
    "PRAGMA",
    "INSERT OR REPLACE INTO",
    "INSERT OR IGNORE INTO",
    "ON CONFLICT DO NOTHING",
    "ON CONFLICT DO UPDATE SET",
    "RETURNING",
    "WITH RECURSIVE",
    "AUTOINCREMENT",
    "WITHOUT ROWID",
    "GLOB",
    "REGEXP",
    "MATCH",
    "COLLATE NOCASE",
    "NULLS FIRST",
    "NULLS LAST",
    "EXPLAIN QUERY PLAN",
    "CREATE VIRTUAL TABLE",
    "CREATE TRIGGER",
    "ATTACH DATABASE",
    "DETACH DATABASE",
    "VACUUM",
    "ANALYZE",
    "REINDEX",
    "BEGIN TRANSACTION",
  ],
  mssql: [
    "TOP",
    "SELECT TOP",
    "OFFSET 0 ROWS",
    "FETCH NEXT",
    "ROWS ONLY",
    "MERGE",
    "OUTPUT",
    "INSERTED",
    "DELETED",
    "CROSS APPLY",
    "OUTER APPLY",
    "PIVOT",
    "UNPIVOT",
    "WITH (NOLOCK)",
    "IDENTITY",
    "NVARCHAR(MAX)",
    "DECLARE",
    "EXEC",
    "GO",
    "SET NOCOUNT ON",
    "BEGIN TRANSACTION",
    "BEGIN TRY",
    "BEGIN CATCH",
    "IF EXISTS",
    "IF OBJECT_ID",
    "CREATE PROCEDURE",
    "ALTER PROCEDURE",
    "CREATE SCHEMA",
  ],
  clickhouse: [
    "PREWHERE",
    "FINAL",
    "SAMPLE",
    "ARRAY JOIN",
    "LEFT ARRAY JOIN",
    "ANY LEFT JOIN",
    "ASOF JOIN",
    "GLOBAL JOIN",
    "LIMIT BY",
    "WITH TOTALS",
    "WITH ROLLUP",
    "WITH CUBE",
    "SETTINGS",
    "FORMAT",
    "FORMAT JSON",
    "FORMAT Pretty",
    "ON CLUSTER",
    "ENGINE = MergeTree",
    "ENGINE = ReplacingMergeTree",
    "PARTITION BY",
    "TTL",
    "SHOW TABLES",
    "SHOW DATABASES",
    "DESCRIBE TABLE",
    "EXISTS TABLE",
    "OPTIMIZE TABLE",
    "ALTER TABLE ... UPDATE",
    "ALTER TABLE ... DELETE",
    "CREATE MATERIALIZED VIEW",
    "ATTACH TABLE",
    "DETACH TABLE",
    "SYSTEM RELOAD",
  ],
};

/** Dialect-only functions, appended after the core. */
const FUNCTION_EXTRAS: Partial<Record<Engine, string[]>> = {
  postgres: [
    "NOW(",
    "GREATEST(",
    "LEAST(",
    "DATE_TRUNC(",
    "EXTRACT(",
    "AGE(",
    "TO_CHAR(",
    "TO_DATE(",
    "TO_TIMESTAMP(",
    "STRING_AGG(",
    "ARRAY_AGG(",
    "JSON_AGG(",
    "JSONB_AGG(",
    "JSONB_BUILD_OBJECT(",
    "JSONB_ARRAY_ELEMENTS(",
    "GENERATE_SERIES(",
    "SPLIT_PART(",
    "REGEXP_REPLACE(",
    "REGEXP_MATCHES(",
    "POSITION(",
    "LEFT(",
    "RIGHT(",
    "LPAD(",
    "MD5(",
    "GEN_RANDOM_UUID(",
    "PERCENTILE_CONT(",
  ],
  mysql: [
    "NOW(",
    "IFNULL(",
    "IF(",
    "CONCAT_WS(",
    "GROUP_CONCAT(",
    "DATE_FORMAT(",
    "STR_TO_DATE(",
    "DATE_ADD(",
    "DATE_SUB(",
    "DATEDIFF(",
    "TIMESTAMPDIFF(",
    "CURDATE(",
    "CURTIME(",
    "UNIX_TIMESTAMP(",
    "FROM_UNIXTIME(",
    "JSON_EXTRACT(",
    "JSON_UNQUOTE(",
    "SUBSTRING_INDEX(",
    "LOCATE(",
    "UUID(",
    "LAST_INSERT_ID(",
  ],
  sqlite: [
    "IFNULL(",
    "IIF(",
    "GROUP_CONCAT(",
    "DATE(",
    "TIME(",
    "DATETIME(",
    "STRFTIME(",
    "JULIANDAY(",
    "UNIXEPOCH(",
    "SUBSTR(",
    "INSTR(",
    "PRINTF(",
    "RANDOM(",
    "HEX(",
    "TYPEOF(",
    "JSON_EXTRACT(",
    "JSON_OBJECT(",
    "JSON_ARRAY(",
    "JSON_GROUP_ARRAY(",
    "TOTAL(",
  ],
  mssql: [
    "GETDATE(",
    "ISNULL(",
    "IIF(",
    "CONVERT(",
    "TRY_CAST(",
    "TRY_CONVERT(",
    "SYSDATETIME(",
    "DATEADD(",
    "DATEDIFF(",
    "DATEPART(",
    "DATENAME(",
    "FORMAT(",
    "LEN(",
    "CHARINDEX(",
    "STUFF(",
    "STRING_AGG(",
    "STRING_SPLIT(",
    "NEWID(",
    "OBJECT_ID(",
    "SCOPE_IDENTITY(",
  ],
  clickhouse: [
    // ClickHouse identifiers are case-sensitive — camelCase is intentional.
    "now(",
    "today(",
    "toDate(",
    "toDateTime(",
    "toString(",
    "toInt64(",
    "toUInt64(",
    "toFloat64(",
    "toStartOfDay(",
    "toStartOfHour(",
    "toStartOfMonth(",
    "formatDateTime(",
    "dateDiff(",
    "uniq(",
    "uniqExact(",
    "any(",
    "anyLast(",
    "argMax(",
    "argMin(",
    "quantile(",
    "quantiles(",
    "countIf(",
    "sumIf(",
    "avgIf(",
    "groupArray(",
    "groupUniqArray(",
    "arrayJoin(",
    "arrayMap(",
    "arrayFilter(",
    "splitByChar(",
    "multiIf(",
    "ifNull(",
    "JSONExtractString(",
  ],
};

/** Keywords to suggest for `engine` (core + dialect extras; CQL stands alone). */
export function keywordsFor(engine: Engine | undefined): string[] {
  if (engine === "cassandra") return CQL_KEYWORDS;
  if (!engine) return CORE_KEYWORDS;
  return [...CORE_KEYWORDS, ...(KEYWORD_EXTRAS[engine] ?? [])];
}

/** Functions to suggest for `engine` (core + dialect extras; CQL stands alone). */
export function functionsFor(engine: Engine | undefined): string[] {
  if (engine === "cassandra") return CQL_FUNCTIONS;
  if (!engine) return CORE_FUNCTIONS;
  return [...CORE_FUNCTIONS, ...(FUNCTION_EXTRAS[engine] ?? [])];
}
