//! Pure, driver-free helpers for the Oracle (PL/SQL) adapter: double-quote
//! identifier quoting, `:N`-placeholder WHERE-clause compilation, Oracle type /
//! default mapping, `OFFSET…FETCH` paging, column-DDL generation, and
//! banner-version formatting. **Nothing here depends on the `oracle` crate**, so
//! this whole module — and its unit tests — compiles and runs in the DEFAULT
//! (pure-Rust, no `engine-oracle` feature) build. The live OCI execution lives
//! in `super::driver` (gated behind the feature).
//!
//! # Why `:N`, not `?` or `@P{n}`
//!
//! Oracle bind variables are written `:1, :2, …` in the SQL text and bound
//! left-to-right by position — the analogue of Postgres' `$1` and SQL Server's
//! `@P1`. The rust-oracle driver binds a positional `&[&dyn ToSql]` against these
//! placeholders. So, like the SQL Server adapter, this module threads a running
//! placeholder index.
//!
//! # Dialect specifics honoured here
//!
//! - Identifiers are **double-quoted** (`"NAME"`), doubling an embedded `"`.
//!   Oracle folds unquoted identifiers to UPPERCASE; introspection returns the
//!   uppercase names, and quoting them preserves the exact catalog name.
//! - Paging is `OFFSET n ROWS FETCH NEXT m ROWS ONLY` (12c+).
//! - Booleans are `NUMBER(1)`; identity is `GENERATED BY DEFAULT AS IDENTITY`;
//!   `SYSTIMESTAMP` / `SYS_GUID()` are the default expressions.

use crate::shared::engine::{Condition, FilterOp, FilterSpec, FilterValue, SortSpec};
use crate::shared::error::AppError;

/// JavaScript's `Number.MAX_SAFE_INTEGER` (2^53 − 1). Oracle `NUMBER` values
/// whose magnitude exceeds this serialize as JSON *strings*, matching the other
/// adapters and the [`crate::shared::engine::QueryResult::rows`] contract.
pub const JS_MAX_SAFE_INTEGER: i64 = 9_007_199_254_740_991;

/// The character used in `ESCAPE '\'` for the LIKE family (matches the other
/// adapters). Oracle honours an arbitrary `ESCAPE` character; we state `\`
/// explicitly (Oracle LIKE has no default escape character).
pub const LIKE_ESCAPE: char = '\\';

/// Quote an identifier for interpolation into Oracle SQL: wrap in double quotes,
/// doubling an embedded quote (`"` → `""`). This is Oracle's delimited-identifier
/// rule, the analogue of SQL Server brackets / MySQL backticks. Because Oracle
/// upper-cases unquoted identifiers, the catalog stores names uppercase and this
/// quoting round-trips them exactly.
pub fn quote_ident(ident: &str) -> String {
    format!("\"{}\"", ident.replace('"', "\"\""))
}

/// `"SCHEMA"."TABLE"`, both identifiers double-quoted. Oracle schemas are users;
/// the default schema is the connected user.
pub fn qualified(schema: &str, table: &str) -> String {
    format!("{}.{}", quote_ident(schema), quote_ident(table))
}

// ---------------------------------------------------------------------------
// Type mapping (generic / Postgres-ish → Oracle) — prototype `toOracleType`
// ---------------------------------------------------------------------------

/// Map a generic / Postgres-ish column type to its Oracle equivalent (the
/// prototype's `toOracleType`, structure.jsx). Case-insensitive; unrecognised
/// types (already-Oracle `NUMBER`/`VARCHAR2`/`DATE`/`CLOB`/…) pass through
/// uppercased. Pure — unit-tested without a live server.
pub fn to_oracle_type(input: &str) -> String {
    let t = input.trim().to_ascii_uppercase();
    // Exact matches first.
    match t.as_str() {
        "BOOL" | "BOOLEAN" => return "NUMBER(1)".to_string(),
        "TEXT" => return "CLOB".to_string(),
        "JSON" | "JSONB" => return "CLOB".to_string(),
        "UUID" => return "RAW(16)".to_string(),
        "TIMESTAMPTZ" => return "TIMESTAMP WITH TIME ZONE".to_string(),
        "TIMESTAMP" => return "TIMESTAMP".to_string(),
        "SERIAL" | "BIGSERIAL" => return "NUMBER".to_string(),
        "SMALLINT" => return "NUMBER(5)".to_string(),
        "INT" | "INTEGER" => return "NUMBER(10)".to_string(),
        "BIGINT" => return "NUMBER(19)".to_string(),
        "DOUBLE PRECISION" => return "BINARY_DOUBLE".to_string(),
        "REAL" => return "BINARY_FLOAT".to_string(),
        "BYTEA" => return "BLOB".to_string(),
        _ => {}
    }
    // Parameterised families (keep the `(…)` suffix).
    if let Some(rest) = t.strip_prefix("NUMERIC") {
        return format!("NUMBER{rest}");
    }
    if let Some(rest) = t.strip_prefix("DECIMAL") {
        return format!("NUMBER{rest}");
    }
    // VARCHAR(n) → VARCHAR2(n). Guard against VARCHAR2(n) already (its char after
    // "VARCHAR" is '2', so it does not match the "VARCHAR(" prefix).
    if let Some(rest) = t.strip_prefix("VARCHAR(") {
        return format!("VARCHAR2({rest}");
    }
    // BINARY(n) → RAW(n).
    if let Some(rest) = t.strip_prefix("BINARY(") {
        return format!("RAW({rest}");
    }
    // CHAR(n) and everything else (already-Oracle types) pass through.
    t
}

/// Translate a Postgres-ish default expression to Oracle (the prototype's
/// `toOracleDefault`). `now()`/`CURRENT_TIMESTAMP` → `SYSTIMESTAMP`;
/// `true`/`false` → `1`/`0`; `gen_random_uuid()`/`uuid_generate_v4()` →
/// `SYS_GUID()`; anything else is kept verbatim. Case-insensitive on the known
/// tokens. Pure — unit-tested.
pub fn to_oracle_default(default: &str) -> String {
    let s = default.trim();
    let lower = s.to_ascii_lowercase();
    match lower.as_str() {
        "now()" | "current_timestamp" => "SYSTIMESTAMP".to_string(),
        "true" => "1".to_string(),
        "false" => "0".to_string(),
        "gen_random_uuid()" | "uuid_generate_v4()" => "SYS_GUID()".to_string(),
        _ => s.to_string(),
    }
}

/// Whether a column type (already an Oracle type, or a length-suffixed one)
/// denotes a numeric column — drives the column-insights numeric display / avg.
/// Oracle numbers are `NUMBER`, `FLOAT`, `BINARY_FLOAT`, `BINARY_DOUBLE` (plus
/// the generic aliases the type dropdown may still carry).
pub fn is_numeric_type(data_type: &str) -> bool {
    let base = data_type
        .split('(')
        .next()
        .unwrap_or(data_type)
        .trim()
        .to_ascii_uppercase();
    matches!(
        base.as_str(),
        "NUMBER"
            | "FLOAT"
            | "BINARY_FLOAT"
            | "BINARY_DOUBLE"
            | "NUMERIC"
            | "DECIMAL"
            | "INTEGER"
            | "INT"
            | "SMALLINT"
            | "BIGINT"
    )
}

// ---------------------------------------------------------------------------
// Column DDL generation (prototype `generateDDL` column line, oracle branch)
// ---------------------------------------------------------------------------

/// A single column's Oracle DDL fragment (the body of a `CREATE TABLE`/`ADD`
/// column list), honouring the Oracle-specific ordering the prototype's
/// `generateDDL(..., 'oracle')` produces:
///
/// - the type is mapped via [`to_oracle_type`];
/// - an integer PK becomes an identity column (`GENERATED BY DEFAULT AS
///   IDENTITY`) and takes **no** DEFAULT;
/// - for a non-identity column a DEFAULT (mapped via [`to_oracle_default`])
///   precedes `NOT NULL` (Oracle requires DEFAULT before the null constraint);
/// - `PRIMARY KEY` is inlined for a single-column pk; a non-pk `NOT NULL` is
///   emitted only when the column is not nullable.
///
/// `raw_type` is the incoming (possibly generic) type; `identity` is whether the
/// caller decided this column is an auto-increment integer pk. Pure — tested.
pub fn column_ddl(
    name: &str,
    raw_type: &str,
    pk: bool,
    nullable: bool,
    default: Option<&str>,
    identity: bool,
) -> String {
    let mut line = format!("{} {}", quote_ident(name), to_oracle_type(raw_type));
    if identity {
        line.push_str(" GENERATED BY DEFAULT AS IDENTITY");
    } else if let Some(d) = default.filter(|d| !d.trim().is_empty()) {
        // DEFAULT precedes NOT NULL in Oracle; identity columns take no DEFAULT.
        line.push_str(" DEFAULT ");
        line.push_str(&to_oracle_default(d));
    }
    if pk {
        line.push_str(" PRIMARY KEY");
    } else if !nullable {
        line.push_str(" NOT NULL");
    }
    line
}

/// The `ON DELETE` suffix Oracle accepts for a foreign key: only `CASCADE` and
/// `SET NULL` (Oracle has no `RESTRICT`/`NO ACTION` keyword — that is the default
/// and is emitted by *omitting* the clause). Returns `""` for any other action.
/// Matches the prototype's FK branch.
pub fn fk_on_delete(action: &str) -> &'static str {
    let a = action.trim().to_ascii_uppercase();
    if a.contains("CASCADE") {
        " ON DELETE CASCADE"
    } else if a.contains("SET NULL") {
        " ON DELETE SET NULL"
    } else {
        ""
    }
}

// ---------------------------------------------------------------------------
// Paging
// ---------------------------------------------------------------------------

/// The Oracle 12c+ row-limiting clause for a page: `OFFSET {offset} ROWS FETCH
/// NEXT {limit} ROWS ONLY`. Values are inlined as integers (never user text), so
/// this needs no bind. An `ORDER BY` should precede it for a stable page (the
/// caller adds one); Oracle allows the clause without ORDER BY but the order is
/// then unspecified.
pub fn paging_clause(offset: u64, limit: u64) -> String {
    format!("OFFSET {offset} ROWS FETCH NEXT {limit} ROWS ONLY")
}

// ---------------------------------------------------------------------------
// Bound values
// ---------------------------------------------------------------------------

/// A single value bound into an Oracle query, in `:N` order. `driver.rs` binds
/// each to the live statement with the right type. JSON-shaped so this module
/// needs no driver types and stays unit-testable.
#[derive(Debug, Clone, PartialEq)]
pub enum BoundValue {
    Null,
    Bool(bool),
    Int(i64),
    Float(f64),
    Text(String),
    Bytes(Vec<u8>),
}

impl BoundValue {
    /// Map a JSON scalar to a bound value for an equality/comparison/`IN`
    /// operand. NULL is rejected (`col = NULL` never matches).
    pub fn from_json_operand(value: &serde_json::Value) -> Result<Self, AppError> {
        match value {
            serde_json::Value::Null => Err(AppError::Database(
                "Use IS NULL / IS NOT NULL to compare with NULL.".to_string(),
            )),
            serde_json::Value::Bool(b) => Ok(Self::Bool(*b)),
            serde_json::Value::Number(n) => {
                if let Some(i) = n.as_i64() {
                    Ok(Self::Int(i))
                } else if let Some(f) = n.as_f64() {
                    Ok(Self::Float(f))
                } else {
                    Ok(Self::Text(n.to_string()))
                }
            }
            serde_json::Value::String(s) => Ok(Self::Text(s.clone())),
            serde_json::Value::Array(_) | serde_json::Value::Object(_) => Err(AppError::Database(
                "A filter value must be a single text, number, or boolean.".to_string(),
            )),
        }
    }

    /// Map a JSON scalar to a bound value for a `SET col = :N` clause. NULL is the
    /// legitimate "set the cell to NULL" case; nested arrays/objects fall back to
    /// their JSON text so the engine decides.
    pub fn from_json_set(value: &serde_json::Value) -> Self {
        match value {
            serde_json::Value::Null => Self::Null,
            other => {
                Self::from_json_operand(other).unwrap_or_else(|_| Self::Text(other.to_string()))
            }
        }
    }

    /// Bind a binary-column operand (filter/pk): the renderer's `0x`-hex / UUID
    /// value decoded to raw bytes. A NULL is rejected like any other operand NULL.
    pub fn from_binary_operand(value: &serde_json::Value) -> Result<Self, AppError> {
        match crate::shared::engine::parse_binary_value(value)? {
            Some(bytes) => Ok(Self::Bytes(bytes)),
            None => Err(AppError::Database(
                "Use IS NULL / IS NOT NULL to compare with NULL.".to_string(),
            )),
        }
    }

    /// Bind a binary-column `SET col = :N` value: decoded bytes, or NULL when the
    /// renderer sends null.
    pub fn from_binary_set(value: &serde_json::Value) -> Result<Self, AppError> {
        Ok(match crate::shared::engine::parse_binary_value(value)? {
            Some(bytes) => Self::Bytes(bytes),
            None => Self::Null,
        })
    }
}

// ---------------------------------------------------------------------------
// WHERE-clause compilation (:N placeholders)
// ---------------------------------------------------------------------------

/// A compiled WHERE clause: the SQL body (without `WHERE`) and the values to
/// bind, in left-to-right `:N` order. `sql == None` means "no predicate".
#[derive(Debug, Default, PartialEq)]
pub struct WhereClause {
    pub sql: Option<String>,
    pub params: Vec<BoundValue>,
}

/// Compile a [`FilterSpec`] into a WHERE body + bound parameters, numbering
/// placeholders from `start_index` (`1` for a standalone WHERE). Returns the
/// clause and the next free placeholder index. Structured conditions bind every
/// value; the raw mode is interpolated verbatim (the documented "Edit as SQL"
/// escape hatch).
pub fn where_clause(
    valid_columns: &[String],
    table: &str,
    filter: &FilterSpec,
    start_index: usize,
) -> Result<(WhereClause, usize), AppError> {
    match filter {
        FilterSpec::Raw { sql } => {
            let trimmed = sql.trim();
            if trimmed.is_empty() {
                return Ok((WhereClause::default(), start_index));
            }
            Ok((
                WhereClause {
                    sql: Some(format!("({trimmed})")),
                    params: Vec::new(),
                },
                start_index,
            ))
        }
        FilterSpec::Conditions { items, combinator } => {
            let mut fragments: Vec<String> = Vec::with_capacity(items.len());
            let mut params: Vec<BoundValue> = Vec::new();
            let mut index = start_index;
            for condition in items {
                let fragment =
                    condition_sql(valid_columns, table, condition, &mut params, &mut index)?;
                fragments.push(fragment);
            }
            if fragments.is_empty() {
                return Ok((WhereClause::default(), start_index));
            }
            let joiner = format!(" {} ", combinator.sql_keyword());
            Ok((
                WhereClause {
                    sql: Some(fragments.join(&joiner)),
                    params,
                },
                index,
            ))
        }
    }
}

/// Compile one [`Condition`] into a SQL fragment, pushing bound values onto
/// `params` and emitting `:{index}` placeholders (advancing `index`).
fn condition_sql(
    valid_columns: &[String],
    table: &str,
    condition: &Condition,
    params: &mut Vec<BoundValue>,
    index: &mut usize,
) -> Result<String, AppError> {
    validate_column(valid_columns, table, &condition.column)?;
    let col = quote_ident(&condition.column);

    match condition.op {
        FilterOp::IsNull => Ok(format!("{col} IS NULL")),
        FilterOp::IsNotNull => Ok(format!("{col} IS NOT NULL")),
        FilterOp::Eq
        | FilterOp::Ne
        | FilterOp::Gt
        | FilterOp::Gte
        | FilterOp::Lt
        | FilterOp::Lte => {
            let value = require_scalar(condition)?;
            params.push(if condition.binary {
                BoundValue::from_binary_operand(value)?
            } else {
                BoundValue::from_json_operand(value)?
            });
            let operator = match condition.op {
                FilterOp::Eq => "=",
                FilterOp::Ne => "<>",
                FilterOp::Gt => ">",
                FilterOp::Gte => ">=",
                FilterOp::Lt => "<",
                FilterOp::Lte => "<=",
                _ => unreachable!("comparison arm"),
            };
            let placeholder = take_placeholder(index);
            Ok(format!("{col} {operator} {placeholder}"))
        }
        FilterOp::Contains | FilterOp::NotContains | FilterOp::BeginsWith | FilterOp::EndsWith => {
            let value = require_scalar(condition)?;
            let text = like_operand(value)?;
            let escaped = escape_like(&text);
            let pattern = match condition.op {
                FilterOp::Contains | FilterOp::NotContains => format!("%{escaped}%"),
                FilterOp::BeginsWith => format!("{escaped}%"),
                FilterOp::EndsWith => format!("%{escaped}"),
                _ => unreachable!("like arm"),
            };
            params.push(BoundValue::Text(pattern));
            let keyword = if matches!(condition.op, FilterOp::NotContains) {
                "NOT LIKE"
            } else {
                "LIKE"
            };
            let placeholder = take_placeholder(index);
            // TO_CHAR so LIKE works on non-text columns too (numeric/date),
            // matching the lax affinity the other adapters give `contains`. The
            // escape char is stated explicitly (Oracle LIKE has no default).
            Ok(format!(
                "TO_CHAR({col}) {keyword} {placeholder} ESCAPE '\\'"
            ))
        }
        FilterOp::InList => {
            let values = match &condition.value {
                Some(FilterValue::List(values)) => values,
                Some(FilterValue::Scalar(_)) => {
                    return Err(AppError::Database(format!(
                        "The 'in list' filter on '{}' needs a list of values.",
                        condition.column
                    )));
                }
                None => return Err(missing_value_error(condition)),
            };
            if values.is_empty() {
                return Err(AppError::Database(format!(
                    "The 'in list' filter on '{}' needs at least one value.",
                    condition.column
                )));
            }
            let mut placeholders = Vec::with_capacity(values.len());
            for value in values {
                params.push(if condition.binary {
                    BoundValue::from_binary_operand(value)?
                } else {
                    BoundValue::from_json_operand(value)?
                });
                placeholders.push(take_placeholder(index));
            }
            Ok(format!("{col} IN ({})", placeholders.join(", ")))
        }
    }
}

/// Emit `:{index}` and advance the counter.
fn take_placeholder(index: &mut usize) -> String {
    let placeholder = format!(":{index}");
    *index += 1;
    placeholder
}

/// The single scalar a comparison / LIKE operator requires (§5 error otherwise).
fn require_scalar(condition: &Condition) -> Result<&serde_json::Value, AppError> {
    match &condition.value {
        Some(FilterValue::Scalar(value)) => Ok(value),
        Some(FilterValue::List(_)) => Err(AppError::Database(format!(
            "The filter on '{}' expects a single value, not a list.",
            condition.column
        ))),
        None => Err(missing_value_error(condition)),
    }
}

fn missing_value_error(condition: &Condition) -> AppError {
    AppError::Database(format!(
        "The filter on '{}' needs a value.",
        condition.column
    ))
}

/// The text operand for a LIKE-family operator. Numbers/bools are stringified;
/// NULL is rejected like any other NULL comparison.
fn like_operand(value: &serde_json::Value) -> Result<String, AppError> {
    match value {
        serde_json::Value::Null => Err(AppError::Database(
            "Use IS NULL / IS NOT NULL to compare with NULL.".to_string(),
        )),
        serde_json::Value::String(s) => Ok(s.clone()),
        serde_json::Value::Bool(b) => Ok(b.to_string()),
        serde_json::Value::Number(n) => Ok(n.to_string()),
        serde_json::Value::Array(_) | serde_json::Value::Object(_) => Err(AppError::Database(
            "A filter value must be a single text, number, or boolean.".to_string(),
        )),
    }
}

/// Escape the LIKE metacharacters (`%`, `_`) and the escape character itself so
/// they match literally under `ESCAPE '\'`.
pub fn escape_like(input: &str) -> String {
    let mut out = String::with_capacity(input.len());
    for ch in input.chars() {
        if ch == LIKE_ESCAPE || ch == '%' || ch == '_' {
            out.push(LIKE_ESCAPE);
        }
        out.push(ch);
    }
    out
}

/// Build the validated, quoted ORDER BY body for a single-column sort:
/// `"COLUMN" ASC|DESC`. The column MUST exist (else a §5 error listing the
/// available columns); the direction is the enum's fixed keyword.
pub fn order_by_clause(
    valid_columns: &[String],
    table: &str,
    sort: &SortSpec,
) -> Result<String, AppError> {
    validate_column(valid_columns, table, &sort.column)?;
    Ok(format!(
        "{} {}",
        quote_ident(&sort.column),
        sort.direction.sql_keyword()
    ))
}

/// Validate that `column` is a real column of the table (§5 error otherwise).
pub fn validate_column(
    valid_columns: &[String],
    table: &str,
    column: &str,
) -> Result<(), AppError> {
    if valid_columns.iter().any(|c| c == column) {
        return Ok(());
    }
    Err(AppError::Database(format!(
        "Column '{column}' does not exist on '{table}' (columns: {}).",
        valid_columns.join(", ")
    )))
}

// ---------------------------------------------------------------------------
// Version formatting
// ---------------------------------------------------------------------------

/// Format the `v$version` banner for the sidebar header. The banner's first line
/// is something like `"Oracle Database 21c Express Edition Release 21.0.0.0.0 -
/// Production"`; we keep the leading `"Oracle Database <edition-ish>"` up to (and
/// including) the version-family token (`19c`/`21c`/`23ai`/…) and drop the
/// trailing "Release … - Production" noise. An empty/odd banner falls back to
/// `"Oracle Database"`.
pub fn display_version(raw: &str) -> String {
    let line = raw.lines().next().unwrap_or(raw).trim();
    if line.is_empty() {
        return "Oracle Database".to_string();
    }
    // Cut at " Release " if present (drops "Release 21.0.0.0.0 - Production").
    let head = match line.find(" Release ") {
        Some(idx) => line[..idx].trim(),
        None => line,
    };
    if head.is_empty() {
        "Oracle Database".to_string()
    } else {
        head.to_string()
    }
}

// ---------------------------------------------------------------------------
// Bulk insert (Oracle `INSERT ALL … SELECT 1 FROM DUAL`)
// ---------------------------------------------------------------------------

/// Build a multi-row insert for M16 bulk generate. Oracle has no multi-`VALUES`
/// syntax, so we emit the `INSERT ALL` form: one `INTO "s"."t" (cols) VALUES
/// (:a, :b)` per row, terminated by `SELECT 1 FROM DUAL`. `n_rows` value groups
/// are emitted; the caller binds `n_rows * columns.len()` values in row-major
/// order against the `:N` placeholders. Pure — unit-tested.
pub fn build_multi_insert_sql(
    schema: &str,
    table: &str,
    columns: &[String],
    n_rows: usize,
) -> String {
    let target = qualified(schema, table);
    let cols_sql = columns
        .iter()
        .map(|c| quote_ident(c))
        .collect::<Vec<_>>()
        .join(", ");
    let mut index = 1usize;
    let mut intos = Vec::with_capacity(n_rows);
    for _ in 0..n_rows {
        let mut placeholders = Vec::with_capacity(columns.len());
        for _ in 0..columns.len() {
            placeholders.push(take_placeholder(&mut index));
        }
        intos.push(format!(
            "INTO {target} ({cols_sql}) VALUES ({})",
            placeholders.join(", ")
        ));
    }
    format!("INSERT ALL {} SELECT 1 FROM DUAL", intos.join(" "))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::shared::engine::{
        Combinator, Condition, FilterOp, FilterSpec, FilterValue, SortDirection,
    };

    fn cols() -> Vec<String> {
        vec![
            "ID".to_string(),
            "NAME".to_string(),
            "QTY".to_string(),
            "weird\"name".to_string(),
        ]
    }

    #[test]
    fn quote_ident_wraps_and_doubles_embedded_quote() {
        assert_eq!(quote_ident("USERS"), "\"USERS\"");
        assert_eq!(quote_ident("a\"b"), "\"a\"\"b\"");
        // A classic injection attempt is neutralized: the closing quote is
        // doubled, so it cannot break out of the identifier.
        assert_eq!(
            quote_ident("x\"; DROP TABLE t; --"),
            "\"x\"\"; DROP TABLE t; --\""
        );
    }

    #[test]
    fn qualified_quotes_both_parts() {
        assert_eq!(qualified("BYTESHOP", "ORDERS"), "\"BYTESHOP\".\"ORDERS\"");
    }

    #[test]
    fn to_oracle_type_maps_generic_and_postgres_types() {
        assert_eq!(to_oracle_type("boolean"), "NUMBER(1)");
        assert_eq!(to_oracle_type("BOOL"), "NUMBER(1)");
        assert_eq!(to_oracle_type("text"), "CLOB");
        assert_eq!(to_oracle_type("json"), "CLOB");
        assert_eq!(to_oracle_type("jsonb"), "CLOB");
        assert_eq!(to_oracle_type("uuid"), "RAW(16)");
        assert_eq!(to_oracle_type("timestamptz"), "TIMESTAMP WITH TIME ZONE");
        assert_eq!(to_oracle_type("timestamp"), "TIMESTAMP");
        assert_eq!(to_oracle_type("smallint"), "NUMBER(5)");
        assert_eq!(to_oracle_type("integer"), "NUMBER(10)");
        assert_eq!(to_oracle_type("int"), "NUMBER(10)");
        assert_eq!(to_oracle_type("bigint"), "NUMBER(19)");
        assert_eq!(to_oracle_type("double precision"), "BINARY_DOUBLE");
        assert_eq!(to_oracle_type("real"), "BINARY_FLOAT");
        assert_eq!(to_oracle_type("bytea"), "BLOB");
        assert_eq!(to_oracle_type("numeric(10,2)"), "NUMBER(10,2)");
        assert_eq!(to_oracle_type("decimal(8)"), "NUMBER(8)");
        assert_eq!(to_oracle_type("varchar(255)"), "VARCHAR2(255)");
        assert_eq!(to_oracle_type("binary(16)"), "RAW(16)");
        assert_eq!(to_oracle_type("char(2)"), "CHAR(2)");
        // Already-Oracle types pass through (uppercased).
        assert_eq!(to_oracle_type("varchar2(4000)"), "VARCHAR2(4000)");
        assert_eq!(to_oracle_type("NUMBER"), "NUMBER");
        assert_eq!(to_oracle_type("clob"), "CLOB");
    }

    #[test]
    fn to_oracle_default_translates_known_expressions() {
        assert_eq!(to_oracle_default("now()"), "SYSTIMESTAMP");
        assert_eq!(to_oracle_default("CURRENT_TIMESTAMP"), "SYSTIMESTAMP");
        assert_eq!(to_oracle_default("true"), "1");
        assert_eq!(to_oracle_default("false"), "0");
        assert_eq!(to_oracle_default("gen_random_uuid()"), "SYS_GUID()");
        assert_eq!(to_oracle_default("uuid_generate_v4()"), "SYS_GUID()");
        // Unknown literals pass through verbatim.
        assert_eq!(to_oracle_default("0"), "0");
        assert_eq!(to_oracle_default("'pending'"), "'pending'");
    }

    #[test]
    fn column_ddl_orders_identity_default_and_notnull() {
        // Integer PK → identity, no default, inline PRIMARY KEY.
        assert_eq!(
            column_ddl("ID", "integer", true, false, None, true),
            "\"ID\" NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        );
        // Non-identity column: DEFAULT precedes NOT NULL, and the default maps.
        assert_eq!(
            column_ddl(
                "CREATED_AT",
                "timestamptz",
                false,
                false,
                Some("now()"),
                false
            ),
            "\"CREATED_AT\" TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL"
        );
        // Nullable column with a boolean default (mapped true→1).
        assert_eq!(
            column_ddl("ACTIVE", "boolean", false, true, Some("true"), false),
            "\"ACTIVE\" NUMBER(1) DEFAULT 1"
        );
        // Plain non-null column, no default.
        assert_eq!(
            column_ddl("NAME", "varchar(255)", false, false, None, false),
            "\"NAME\" VARCHAR2(255) NOT NULL"
        );
    }

    #[test]
    fn fk_on_delete_limits_to_cascade_and_set_null() {
        assert_eq!(fk_on_delete("CASCADE"), " ON DELETE CASCADE");
        assert_eq!(fk_on_delete("cascade"), " ON DELETE CASCADE");
        assert_eq!(fk_on_delete("SET NULL"), " ON DELETE SET NULL");
        // RESTRICT / NO ACTION → omit (Oracle default).
        assert_eq!(fk_on_delete("RESTRICT"), "");
        assert_eq!(fk_on_delete("NO ACTION"), "");
        assert_eq!(fk_on_delete(""), "");
    }

    #[test]
    fn paging_clause_uses_offset_fetch() {
        assert_eq!(
            paging_clause(40, 20),
            "OFFSET 40 ROWS FETCH NEXT 20 ROWS ONLY"
        );
    }

    #[test]
    fn is_numeric_type_classifies_oracle_types() {
        for t in [
            "NUMBER",
            "NUMBER(10)",
            "FLOAT",
            "BINARY_FLOAT",
            "BINARY_DOUBLE",
            "integer",
        ] {
            assert!(is_numeric_type(t), "{t} should be numeric");
        }
        for t in [
            "VARCHAR2(255)",
            "CLOB",
            "DATE",
            "TIMESTAMP",
            "RAW(16)",
            "BLOB",
        ] {
            assert!(!is_numeric_type(t), "{t} should not be numeric");
        }
    }

    #[test]
    fn display_version_keeps_edition_drops_release_noise() {
        assert_eq!(
            display_version("Oracle Database 21c Express Edition Release 21.0.0.0.0 - Production"),
            "Oracle Database 21c Express Edition"
        );
        assert_eq!(
            display_version(
                "Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production"
            ),
            "Oracle Database 19c Enterprise Edition"
        );
        assert_eq!(display_version(""), "Oracle Database");
    }

    #[test]
    fn multi_insert_uses_insert_all_and_numbered_binds() {
        let sql = build_multi_insert_sql("BYTESHOP", "T", &["A".into(), "B".into()], 2);
        assert_eq!(
            sql,
            "INSERT ALL INTO \"BYTESHOP\".\"T\" (\"A\", \"B\") VALUES (:1, :2) \
             INTO \"BYTESHOP\".\"T\" (\"A\", \"B\") VALUES (:3, :4) SELECT 1 FROM DUAL"
        );
    }

    #[test]
    fn escape_like_escapes_metacharacters() {
        assert_eq!(escape_like("100%"), "100\\%");
        assert_eq!(escape_like("a_b"), "a\\_b");
        assert_eq!(escape_like("c\\d"), "c\\\\d");
        assert_eq!(escape_like("plain"), "plain");
    }

    #[test]
    fn order_by_validates_and_quotes() {
        let sort = SortSpec {
            column: "NAME".into(),
            direction: SortDirection::Desc,
        };
        assert_eq!(
            order_by_clause(&cols(), "t", &sort).unwrap(),
            "\"NAME\" DESC"
        );
        let bad = SortSpec {
            column: "nope".into(),
            direction: SortDirection::Asc,
        };
        assert!(matches!(
            order_by_clause(&cols(), "t", &bad),
            Err(AppError::Database(_))
        ));
    }

    #[test]
    fn where_clause_comparison_emits_numbered_bind() {
        let spec = FilterSpec::Conditions {
            items: vec![Condition {
                column: "QTY".into(),
                op: FilterOp::Gte,
                value: Some(FilterValue::Scalar(serde_json::json!(10))),
                binary: false,
            }],
            combinator: Combinator::And,
        };
        let (wc, next) = where_clause(&cols(), "t", &spec, 1).unwrap();
        assert_eq!(wc.sql.as_deref(), Some("\"QTY\" >= :1"));
        assert_eq!(wc.params, vec![BoundValue::Int(10)]);
        assert_eq!(next, 2);
    }

    #[test]
    fn where_clause_multiple_conditions_number_binds_in_order() {
        let spec = FilterSpec::Conditions {
            items: vec![
                Condition {
                    column: "NAME".into(),
                    op: FilterOp::Eq,
                    value: Some(FilterValue::Scalar(serde_json::json!("ada"))),
                    binary: false,
                },
                Condition {
                    column: "ID".into(),
                    op: FilterOp::InList,
                    value: Some(FilterValue::List(vec![
                        serde_json::json!(1),
                        serde_json::json!(2),
                    ])),
                    binary: false,
                },
                Condition {
                    column: "QTY".into(),
                    op: FilterOp::Gt,
                    value: Some(FilterValue::Scalar(serde_json::json!(5))),
                    binary: false,
                },
            ],
            combinator: Combinator::And,
        };
        let (wc, next) = where_clause(&cols(), "t", &spec, 1).unwrap();
        assert_eq!(
            wc.sql.as_deref(),
            Some("\"NAME\" = :1 AND \"ID\" IN (:2, :3) AND \"QTY\" > :4")
        );
        assert_eq!(next, 5);
        assert_eq!(
            wc.params,
            vec![
                BoundValue::Text("ada".into()),
                BoundValue::Int(1),
                BoundValue::Int(2),
                BoundValue::Int(5),
            ]
        );
    }

    #[test]
    fn where_clause_contains_to_char_and_escapes() {
        let spec = FilterSpec::Conditions {
            items: vec![Condition {
                column: "NAME".into(),
                op: FilterOp::Contains,
                value: Some(FilterValue::Scalar(serde_json::json!("a%b"))),
                binary: false,
            }],
            combinator: Combinator::And,
        };
        let (wc, _) = where_clause(&cols(), "t", &spec, 1).unwrap();
        assert_eq!(
            wc.sql.as_deref(),
            Some("TO_CHAR(\"NAME\") LIKE :1 ESCAPE '\\'")
        );
        assert_eq!(wc.params, vec![BoundValue::Text("%a\\%b%".into())]);
    }

    #[test]
    fn injection_payload_binds_as_a_literal_not_sql() {
        let spec = FilterSpec::Conditions {
            items: vec![Condition {
                column: "NAME".into(),
                op: FilterOp::Eq,
                value: Some(FilterValue::Scalar(serde_json::json!(
                    "'; DROP TABLE t; --"
                ))),
                binary: false,
            }],
            combinator: Combinator::And,
        };
        let (wc, _) = where_clause(&cols(), "t", &spec, 1).unwrap();
        assert_eq!(wc.sql.as_deref(), Some("\"NAME\" = :1"));
        assert_eq!(
            wc.params,
            vec![BoundValue::Text("'; DROP TABLE t; --".into())]
        );
    }

    #[test]
    fn where_clause_unknown_column_is_a_human_error() {
        let spec = FilterSpec::Conditions {
            items: vec![Condition {
                column: "ghost".into(),
                op: FilterOp::Eq,
                value: Some(FilterValue::Scalar(serde_json::json!(1))),
                binary: false,
            }],
            combinator: Combinator::And,
        };
        let err = where_clause(&cols(), "t", &spec, 1).unwrap_err();
        assert!(matches!(err, AppError::Database(_)));
        assert!(err.to_string().contains("ghost"));
    }
}
