-- Oracle (PL/SQL) seed — run MANUALLY as SYSTEM against the Docker Oracle (the
-- images have no drop-in initdb dir for multi-user setups). The compose service
-- uses `gvenzl/oracle-free:23-slim` (native arm64, PDB `FREEPDB1`). Connect e.g.
--   sqlplus system/ByteTable1!@//localhost:11521/FREEPDB1 @seed/oracle.sql
-- (For an amd64 `gvenzl/oracle-xe` box the PDB is `XEPDB1` instead.)
-- Creates the BYTESHOP / SALES / AUDIT user-schemas (Oracle "schemas are users",
-- uppercase), an e-commerce + audit dataset, and the full object set (view /
-- materialized view / function / procedure / trigger) so the M23 acceptance
-- surfaces have real data: FK hop, structure view, column insights, NUMBER(1)
-- booleans, GENERATED AS IDENTITY, NUMBER money, RAW(16)/BLOB binary, CLOB JSON.
-- Idempotent: drops + recreates the users, so re-running re-seeds cleanly.

SET DEFINE OFF;

-- ── Users = schemas (drop + recreate for a clean re-seed). The DROPs swallow
-- "user does not exist" so a first run is clean; everything after fails loud. ──
BEGIN EXECUTE IMMEDIATE 'DROP USER byteshop CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP USER sales CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP USER "AUDIT" CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

WHENEVER SQLERROR EXIT SQL.SQLCODE;

-- AUDIT is an Oracle reserved word, so the audit user MUST be quoted ("AUDIT");
-- Oracle stores it uppercase, and the app quotes identifiers, so it round-trips.
CREATE USER byteshop IDENTIFIED BY "ByteTable1!" QUOTA UNLIMITED ON users;
CREATE USER sales    IDENTIFIED BY "ByteTable1!" QUOTA UNLIMITED ON users;
CREATE USER "AUDIT"  IDENTIFIED BY "ByteTable1!" QUOTA UNLIMITED ON users;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE MATERIALIZED VIEW,
      CREATE PROCEDURE, CREATE TRIGGER, CREATE SEQUENCE TO byteshop;
GRANT CREATE SESSION, CREATE TABLE TO sales;
GRANT CREATE SESSION, CREATE TABLE TO "AUDIT";

ALTER SESSION SET CURRENT_SCHEMA = BYTESHOP;

-- ── Core tables (BYTESHOP) — identity pks, NUMBER(1) booleans, NUMBER money. ──
CREATE TABLE byteshop.users (
  id         NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR2(120) NOT NULL,
  email      VARCHAR2(160) UNIQUE,
  country    VARCHAR2(2),
  active     NUMBER(1) DEFAULT 1 NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE TABLE byteshop.products (
  id    NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku   VARCHAR2(32) NOT NULL UNIQUE,
  name  VARCHAR2(120) NOT NULL,
  price NUMBER(10,2) DEFAULT 0 NOT NULL
);
CREATE TABLE byteshop.orders (
  id      NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id NUMBER(10) NOT NULL CONSTRAINT fk_orders_users REFERENCES byteshop.users(id) ON DELETE CASCADE,
  total   NUMBER(10,2),
  status  VARCHAR2(20),
  method  VARCHAR2(20),
  paid    NUMBER(1)
);
CREATE INDEX byteshop.idx_orders_user ON byteshop.orders(user_id);
CREATE TABLE byteshop.order_items (
  id         NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id   NUMBER(10) NOT NULL CONSTRAINT fk_items_orders REFERENCES byteshop.orders(id) ON DELETE CASCADE,
  product_id NUMBER(10) NOT NULL CONSTRAINT fk_items_products REFERENCES byteshop.products(id),
  qty        NUMBER(10) DEFAULT 1 NOT NULL
);

-- ── RAW(16) + CLOB demo (binary cells, JSON viewer, binary FK, SYS_GUID). ──
CREATE TABLE byteshop.accounts (
  id         RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
  handle     VARCHAR2(64) NOT NULL,
  prefs      CLOB,
  avatar     RAW(16),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE TABLE byteshop.documents (
  id         RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
  account_id RAW(16) NOT NULL CONSTRAINT fk_docs_accounts REFERENCES byteshop.accounts(id) ON DELETE CASCADE,
  title      VARCHAR2(160) NOT NULL,
  body       CLOB,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE INDEX byteshop.idx_documents_account ON byteshop.documents(account_id);

-- ── sales / audit schemas (multi-schema switcher + cross-schema FK hop). ──
-- A cross-schema FK requires the CHILD schema to hold REFERENCES on the parent
-- table (Oracle checks the privilege against the table owner, not the DBA
-- running this) — without it the CREATE fails with a masked ORA-00942.
GRANT REFERENCES ON byteshop.orders TO sales;
GRANT REFERENCES ON byteshop.users  TO "AUDIT";
CREATE TABLE sales.invoices (
  id       NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id NUMBER(10) NOT NULL CONSTRAINT fk_invoices_orders REFERENCES byteshop.orders(id),
  amount   NUMBER(12,2) NOT NULL,
  issued   DATE DEFAULT SYSDATE NOT NULL
);
CREATE TABLE "AUDIT".events (
  id      NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind    VARCHAR2(40) NOT NULL,
  user_id NUMBER(10) CONSTRAINT fk_events_users REFERENCES byteshop.users(id),
  ts      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- ── Seed rows (identity assigns 1-based ids on a fresh table → stable FKs). ──
INSERT INTO byteshop.users (name, email, country, active) VALUES ('Ada Lovelace',    'ada@byteshop.io',    'GB', 1);
INSERT INTO byteshop.users (name, email, country, active) VALUES ('Alan Turing',     'alan@byteshop.io',   'GB', 1);
INSERT INTO byteshop.users (name, email, country, active) VALUES ('Grace Hopper',    'grace@byteshop.io',  'US', 1);
INSERT INTO byteshop.users (name, email, country, active) VALUES ('Edsger Dijkstra', 'edsger@byteshop.io', 'NL', 0);
INSERT INTO byteshop.products (sku, name, price) VALUES ('MUG-01', 'ByteTable Mug', 12.50);
INSERT INTO byteshop.products (sku, name, price) VALUES ('TEE-01', 'Logo T-Shirt',  24.00);
INSERT INTO byteshop.products (sku, name, price) VALUES ('STK-01', 'Sticker Pack',   5.00);
INSERT INTO byteshop.orders (user_id, total, status, method, paid) VALUES (1, 42.50, 'delivered', 'card',   1);
INSERT INTO byteshop.orders (user_id, total, status, method, paid) VALUES (1, 19.99, 'shipped',   'card',   1);
INSERT INTO byteshop.orders (user_id, total, status, method, paid) VALUES (2, 99.00, 'pending',   'paypal', 0);
INSERT INTO byteshop.orders (user_id, total, status, method, paid) VALUES (3,  5.00, 'cancelled', 'card',   0);
INSERT INTO byteshop.orders (user_id, total, status, method, paid) VALUES (3, 36.50, 'delivered', 'paypal', 1);
INSERT INTO byteshop.order_items (order_id, product_id, qty) VALUES (1,1,2);
INSERT INTO byteshop.order_items (order_id, product_id, qty) VALUES (1,3,1);
INSERT INTO byteshop.order_items (order_id, product_id, qty) VALUES (2,2,1);
INSERT INTO byteshop.order_items (order_id, product_id, qty) VALUES (3,2,3);
INSERT INTO byteshop.order_items (order_id, product_id, qty) VALUES (5,1,1);
INSERT INTO byteshop.order_items (order_id, product_id, qty) VALUES (5,3,2);
INSERT INTO sales.invoices (order_id, amount) VALUES (1, 42.50);
INSERT INTO sales.invoices (order_id, amount) VALUES (2, 19.99);
INSERT INTO sales.invoices (order_id, amount) VALUES (5, 36.50);
INSERT INTO "AUDIT".events (kind, user_id) VALUES ('login', 1);
INSERT INTO "AUDIT".events (kind, user_id) VALUES ('view', 1);
INSERT INTO "AUDIT".events (kind, user_id) VALUES ('purchase', 2);

-- Deterministic GUIDs so the FK hop / binary filter demos are reproducible.
INSERT INTO byteshop.accounts (id, handle, prefs, avatar) VALUES
  (HEXTORAW('11111111111141118111111111111111'), 'ada',
   '{"theme":"midnight","notifications":{"email":true,"push":false},"tags":["admin","early-access"]}',
   HEXTORAW('DEADBEEF'));
INSERT INTO byteshop.accounts (id, handle, prefs, avatar) VALUES
  (HEXTORAW('22222222222242228222222222222222'), 'grace',
   '{"theme":"light","notifications":{"email":false,"push":true},"tags":[]}',
   HEXTORAW('CAFEBABE'));
INSERT INTO byteshop.documents (id, account_id, title, body) VALUES
  (HEXTORAW('AAAAAAAAAAAA4AAA8AAAAAAAAAAAAAAA'), HEXTORAW('11111111111141118111111111111111'),
   'Q3 Roadmap', '{"status":"published","wordCount":1280,"reviewers":["grace","alan"]}');
INSERT INTO byteshop.documents (id, account_id, title, body) VALUES
  (HEXTORAW('BBBBBBBBBBBB4BBB8BBBBBBBBBBBBBBB'), HEXTORAW('11111111111141118111111111111111'),
   'Release Notes', '{"status":"draft","wordCount":340,"reviewers":[]}');
INSERT INTO byteshop.documents (id, account_id, title, body) VALUES
  (HEXTORAW('CCCCCCCCCCCC4CCC8CCCCCCCCCCCCCCC'), HEXTORAW('22222222222242228222222222222222'),
   'Design Spec', '{"status":"review","wordCount":2110,"reviewers":["ada"]}');
COMMIT;

-- ── Schema objects (object browser: view / matview / function / proc / trigger). ──
-- In a sqlplus script each statement is run by EITHER a trailing `;` OR a lone
-- `/` — never both (both = run twice; the MV's second run hits ORA-00955 and,
-- under WHENEVER SQLERROR EXIT, aborts the rest). Views/MV use `/` only here;
-- the PL/SQL routines below use `/` after their `END;`.
CREATE OR REPLACE VIEW byteshop.active_users AS
  SELECT id, name, email, country FROM byteshop.users WHERE active = 1
/

-- Real materialized view (surfaced under the "Materialized Views" section).
CREATE MATERIALIZED VIEW byteshop.order_totals
  BUILD IMMEDIATE
  REFRESH COMPLETE ON DEMAND AS
  SELECT user_id, COUNT(*) AS orders
  FROM byteshop.orders
  GROUP BY user_id
/

CREATE OR REPLACE FUNCTION byteshop.user_order_count(p_uid IN NUMBER)
RETURN NUMBER IS
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM byteshop.orders WHERE user_id = p_uid;
  RETURN v_count;
END;
/

CREATE OR REPLACE PROCEDURE byteshop.deactivate_user(p_uid IN NUMBER) AS
BEGIN
  UPDATE byteshop.users SET active = 0 WHERE id = p_uid;
END;
/

CREATE OR REPLACE TRIGGER byteshop.orders_touch
BEFORE INSERT ON byteshop.orders
FOR EACH ROW
BEGIN
  NULL; -- no-op audit hook
END;
/

EXIT;
